# config/secrets.yml
development:
  stripe:
    publishable_key: pk_test_51JSzevFZOoqTAj1QDPyYtR0gNfIlwcrIGMYbn0n2Iftsa50J87OoxwoY7LziuIL19wp9VRey7iyKVzu3Y17O2hKK00JpL8EBZZ
    secret_key: sk_test_51JSzevFZOoqTAj1QKe7TfBqbrvzqgEHeQd17v1KnKXYYOiW5CDSaroeLANAQVYFAEI5y7yfhfHKWZHtch6SYwt1f00aQsXOUos

test: &development

#production:
#  stripe:
#    publishable_key: pk_test_51JSzevFZOoqTAj1QDPyYtR0gNfIlwcrIGMYbn0n2Iftsa50J87OoxwoY7LziuIL19wp9VRey7iyKVzu3Y17O2hKK00JpL8EBZZ
#    secret_key: sk_test_51JSzevFZOoqTAj1QKe7TfBqbrvzqgEHeQd17v1KnKXYYOiW5CDSaroeLANAQVYFAEI5y7yfhfHKWZHtch6SYwt1f00aQsXOUos
