# config/secrets.yml
development:
  stripe:
    premium_plan_id: premium-monthly
    publishable_key: pk_test_51KCKVmJ2YKllwOoi31I89iev0wAlH6JCrC3d0G53oLjnGFbsMeSXx55NNU7AZua1R3yIfKe81GTSCmnAnm7TD2bA008gfOmxDJ
    secret_key: sk_test_51KCKVmJ2YKllwOoiHO6NbQ1R4FHf5IPHgPRyImMQBcrnboyomYQwSB4RgXPGMiQvK5yE6sL0bP3TA1YjXQE6v84G001EZSwk7H

test: &development

production:
  stripe:
    premium_plan_id: premium-monthly
    publishable_key: pk_live_51KCKVmJ2YKllwOoiNmRB2QdOUsJxvRJAtWZq3X5WhAq0aASldENO04W5MetSDfXzCs7MB6KtYORUwkgugPWhYLim00UAa9GpkB
    secret_key: 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
